import base64
import struct

# Command '"hi" * 64KB'

responses = [
    # Are compressed, contains the pipeline output '<S>hihihihihi....'
    # 307 bytes
    '/38uAWMGBWAAAAAABQAAAAAAAAAAYAAABmAAAGBgAGBlAAYGAAYAAAAAUAAAYAAABgAGAAAAAABmYAYAAAAAAAAAAGBgAAYAAAYAAAAAAAAGAAAAAAAAAAAAAAYAAAAAAGAAYAAAAGAAAAAAYABgAAAAAAYAAAYGAGAAYGAAAABQAAAABlUAAAAAAAAAAAAAAAAAUAUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABxClqC7wKCGIIUzZjvM3xE1IsjGFmEbbZH/cUn997XtO7DyZq1PLdWAOD/uH8AAA==',
    # 273 bytes
    '/38MAUQAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABEAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAANDAAAAAAAAAAAAAAAAAAMAMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABMg80StOwA8P/mfwAA',
    # 273 bytes
    '/38MAQQEAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABEAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAANDAAAAAAAAAAAAAAAAAAMAMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABMg80SxOsA8P/mfwAA',
    # 273 bytes
    '/38MAQRAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABEAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAANDAAAAAAAAAAAAAAAAAAMAMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABMg80StOwA8P/mfwAA',

    #  The following are not compressed.
    # '...hihihihi</s>'
    # 159 bytes
    'mgCaAAAAAAAAAAAHAAAAAAAAAAQCAAAAhmhpaGloaWhpaGloaWhpaGloaWhpaGloaWhpaGloaWhpaGloaWhpaGloaWhpaGloaWhpaGloaWhpaGloaWhpaGloaWhpaGloaWhpaGloaWhpaGloaWhpaGloaWhpaGloaWhpaGloaWhpaGloaWhpaGloaWhpaGloaWhpaGloaWhpaGk8L1M+',
    # Contains pipeline state '<Obj RefId="0"><MS><I32 N="PipelineState">4</I32></MS></Obj>'
    # 128 bytes
    'ewB7AAAAAAAAAAAIAAAAAAAAAAADAAAAZwEAAAAGEAQAXDk4QisoN02YEOQxhPnV+WvHrgLxWN5NiiPm0Ww4gTPvu788T2JqIFJlZklkPSIwIj48TVM+PEkzMiBOPSJQaXBlbGluZVN0YXRlIj40PC9JMzI+PC9NUz48L09iaj4=',
]

# Hex of first 4 responses
# b'FF7F2E0163060560
# b'FF7F0C0144000040
# b'FF7F0C0104040040
# b'FF7F0C0104400040

# The first 4 bytes represent the length of the original message -1 and the length of the compressed message – 1. Anything smaller than 266 bytes is not compressed.
# 32767:302
# 32767:268
# 32767:268
# 32767:268

# Actual response would be '<S>hi * 64KB'
# 131079 (CLIXML)
# 21 fragement
# 40 object
# 3 (BOM)
# 131143 (total bytes)

compressed = base64.b64decode(responses[1])

actual = ''
expected = 'hi' * 16384

assert actual == expected
